### ISSUE TITLE
There are some english titles and descriptions in the tables in the Nextcloud installation Guide.

### ISSUE THREAD

**Issue by 3incognito** [zap-docs/docs#1281]
### Which documents (guides) is your report about?

https://zap-hosting.com/guides/de/docs/vserver-linux-nextcloud/

### Which content is incorrect or out of date?

Just the translation
![screenshot](https://github.com/user-attachments/assets/dfb54f53-655d-4133-a88d-4e9abf5fa1c8)

### What changes need to be made?

Translating all English titles and descriptions to German.

### By submitting this form, you agree that...

- [X] You have filled in the form to the best of your ability.
- [X] You confirm that the error still exists and have referenced it appropriately.

**Comment by ThatGuyJacobee** [comment]
@fgalz BTW, I have adjusted this in #1282 so feel free to further adjust it in the PR if there is anything else you want to change :^)
